server.port=8080
spring.application.name=api-gateway
spring.cloud.discovery.enabled=false

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=forum-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/topicos/**,/api/comentarios/**

spring.cloud.gateway.routes[2].id=algorithm-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/exercicios/**,/api/submissoes/**

spring.cloud.gateway.routes[3].id=gamification-service-pontos
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/pontos/**

spring.cloud.gateway.routes[4].id=gamification-service-ranking
spring.cloud.gateway.routes[4].uri=http://localhost:8084
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/ranking/**

spring.cloud.gateway.routes[5].id=personalization-service
spring.cloud.gateway.routes[5].uri=http://localhost:8085
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/sugestoes/**

jwt.secret=ifsp-guarulhos-ads-apis-microsservicos-2026-secret-key